POST http://localhost:3000/auth/signup HTTP/1.1
Content-Type: application/json

{
    "name": "pedro"
}

###
POST http://localhost:3000/auth/signin HTTP/1.1
Content-Type: application/json

{
    "username": "detectabledeclaration",
    "password": "165718"
}